version: '3.8'

services:
  chat-server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add your Firebase environment variables here
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped
